#==============================================================================#
# box-base
#==============================================================================#

# Keep the Fedora release aligned with the host and containers/smb-box/Containerfile.
# On a host release upgrade, update both pins and rebuild all boxes (README.md).
FROM registry.fedoraproject.org/fedora:44 AS box-base

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=1000

COPY rootfs/base /

RUN sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/fedora-cisco-openh264.repo

# Reinstall base packages with documentation included.
RUN --mount=type=cache,target=/var/cache/libdnf5,sharing=locked \
    dnf upgrade -y && \
    dnf reinstall -y --setopt=keepcache=1 \
    $(rpm -qa --queryformat '%{NAME}\n' | grep -v gpg-pubkey) && \
    rm -rf /var/log/dnf*

RUN --mount=type=cache,target=/var/cache/libdnf5,sharing=locked \
    dnf install -y --setopt=keepcache=1 \
    ca-certificates curl \
    fish git man-db openssh-clients tar unzip which \
    gcc gcc-c++ make cmake pkgconfig \
    procps-ng psmisc perf sudo && \
    rm -rf /var/log/dnf*

RUN groupadd -g "$USER_GID" "$USERNAME" && \
    useradd -m -u "$USER_UID" -g "$USER_GID" -s /usr/bin/fish "$USERNAME" && \
    echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudo-nopasswd && \
    chmod 0440 /etc/sudoers.d/sudo-nopasswd

RUN ln -s /home /var/home

#==============================================================================#
# dev-box
#==============================================================================#

FROM box-base AS dev-box

COPY rootfs/dev-box /

RUN --mount=type=cache,target=/var/cache/libdnf5,sharing=locked \
    dnf install -y --setopt=keepcache=1 openssh-server && \
    rm -rf /var/log/dnf*

USER root

CMD ["/usr/local/sbin/dev-box-run"]
