#!/usr/bin/env fish

echo "Notify at $(date '+%Y-%m-%d %H:%M:%S')"

# Setup the background color of neovim based on the current theme
if type -q nvim; and type -q nvr
    set -l nvim_bg
    if test $DARKMODE -eq 1
        set nvim_bg dark
    else
        set nvim_bg light
    end
    for server in (nvr --serverlist)
        nvr --servername $server +"set bg=$nvim_bg"
    end
end

if test $DARKMODE -eq 1
    set bg dark
    set theme macchiato
else
    set bg light
    set theme latte
end

# Setup some environment variables read by some cli tools by set fish Universal Variables
if type -q delta
    set -Ux DELTA_FEATURES $theme
end
