[".config/bat/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/bat.git"
refreshPeriod = "168h"
clone.args = ["--filter=blob:none"]
pull.args = ["--ff-only"]
[".config/kitty/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/kitty.git"
refreshPeriod = "168h"
clone.args = ["--filter=blob:none"]
pull.args = ["--ff-only"]
