[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }

[[tasks]]
type = "Roguelike"

[tasks.params]
core_char = "维什戴尔"
roles = "稳扎稳打"
mode = 0
investment_enabled = false

[tasks.params.theme]
alternatives = ["Mizuki", "Sami", "Sarkaz"]
default_index = 3
description = "theme"

[tasks.params.squad]
alternatives = ["指挥分队", "远程战术分队", "蓝图测绘分队"]
default_index = 3
description = "squad"

[[tasks]]
type = "CloseDown"
