#!/usr/bin/env bash

# check if yadm is installed
if ! command -v yadm &> /dev/null; then
    echo "Using yadm remotely to bootstrap"
    source <(curl -L bootstrap.yadm.io)
fi

# init yadm submodule
yadm submodule update --init --recursive

# sparse checkout to avoid  README.md and LICENSE in HOME
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!LICENSE'
