"""Plan owned chezmoi sources without changing the filesystem."""

import re
from pathlib import Path
from typing import Literal

from .models import BUNDLE_ROOT, PackageError, PortableManifest

# chezmoi strips source state attributes from every source path component, so a
# target directory named `private_tools` would otherwise deploy to `tools`.
ATTRIBUTE_PREFIX_RE = re.compile(r"^[a-z]+_")
SourceKind = Literal["symlink", "remove"]


def source_directory(part: str) -> str:
    """Encode one target directory name as a chezmoi source directory name.

    A leading dot keeps chezmoi's `dot_` convention; every other attribute-like
    prefix is quoted with `literal_`, which stops further attribute parsing.
    """
    if part.startswith("."):
        return f"dot_{part[1:]}"
    if ATTRIBUTE_PREFIX_RE.match(part):
        return f"literal_{part}"
    return part


class PackageSources:
    """Manage generated bundle links and retired destinations for every package type."""

    LINK_CONTENT = '{{- template "portable-pkgs-link.tmpl" . -}}\n'
    REMOVE_CONTENT = "Generated by portable-pkgs: remove this retired destination.\n"

    def __init__(self, manifest_path: Path) -> None:
        self.manifest_path = manifest_path.absolute()
        self.root = self.manifest_path.parent.parent

    @staticmethod
    def links(manifest: PortableManifest | None) -> set[str]:
        if manifest is None:
            return set()
        return {
            f"{manifest.install_dir}/{bin_name}"
            for tool in manifest.tools.values()
            if tool.type == "bundle"
            for bin_name in tool.bin_names()
        }

    @staticmethod
    def destinations(manifest: PortableManifest | None) -> set[str]:
        if manifest is None:
            return set()
        return {
            f"{manifest.install_dir}/{bin_name}"
            for tool in manifest.tools.values()
            for bin_name in tool.bin_names()
        } | {
            f"{BUNDLE_ROOT}/{name}"
            for name, tool in manifest.tools.items()
            if tool.type == "bundle"
        }

    def source_path(self, target: str, kind: SourceKind) -> Path:
        parts = Path(target).parts
        directories = [source_directory(part) for part in parts[:-1]]
        command = parts[-1]
        if kind == "remove":
            filename = f"remove_literal_{command}.literal"
        else:
            if command.startswith(("dot_", "literal_")):
                command = f"literal_{command}"
            filename = f"symlink_{command}.tmpl"
        path = self.root.joinpath(*directories, filename)
        if not path.parent.resolve().is_relative_to(self.root.resolve()):
            raise PackageError(f"package source escapes source directory: {path}")
        return path

    def plan(
        self, before: PortableManifest | None, after: PortableManifest
    ) -> dict[Path, str | None]:
        old_links, new_links = self.links(before), self.links(after)
        previous = self.destinations(before)
        active = self.destinations(after)
        retired = previous - active
        desired: dict[Path, SourceKind] = {
            self.source_path(target, kind): kind
            for kind, targets in (
                ("symlink", new_links),
                ("remove", retired),
            )
            for target in targets
        }
        obsolete: dict[Path, SourceKind] = {
            path: kind
            for kind, targets in (
                ("symlink", old_links - new_links),
                ("remove", active),
            )
            for target in targets
            if (path := self.source_path(target, kind)).exists() or path.is_symlink()
        }
        if not desired and not obsolete:
            return {}
        if self.manifest_path.parent.name != ".chezmoidata":
            raise PackageError(
                "source updates require a manifest inside the chezmoi "
                "source .chezmoidata directory"
            )
        changes: dict[Path, str | None] = {}
        sources = desired | obsolete
        for path, kind in sources.items():
            expected = self.REMOVE_CONTENT if kind == "remove" else self.LINK_CONTENT
            if path.is_symlink() or (
                path.exists() and (not path.is_file() or path.read_text() != expected)
            ):
                raise PackageError(f"package source is not owned or was edited: {path}")
            if path in obsolete:
                changes[path] = None
            elif not path.exists():
                changes[path] = expected
        # Remove the old source before creating its replacement at the same target.
        return dict(sorted(changes.items(), key=lambda item: item[1] is not None))
