#!/usr/bin/env bash

set -euo pipefail

remove_file() {
    local path=$1

    if [ -e "$path" ] || [ -L "$path" ]; then
        rm -f "$path"
        echo "Removed stale aqua migration file: $path"
    fi
}

remove_aqua_proxy_link() {
    local link=$1
    local target

    if [ ! -L "$link" ]; then
        return
    fi

    target=$(readlink "$link" || true)
    case "$target" in
        *aqua-proxy*)
            rm -f "$link"
            echo "Removed stale aqua proxy link: $link"
            ;;
    esac
}

remove_old_starship_fish_config() {
    local path=$HOME/.config/fish/conf.d/95-starship.fish

    if [ ! -e "$path" ] && [ ! -L "$path" ]; then
        return
    fi

    if grep -Fq "Generated by chezmoi from the aqua-managed starship package." "$path"; then
        rm -f "$path"
        echo "Removed stale aqua-managed starship fish config: $path"
    else
        echo "Keeping user-modified starship fish config: $path"
    fi
}

remove_empty_dir() {
    local path=$1

    if [ -d "$path" ]; then
        rmdir "$path" 2>/dev/null || true
    fi
}

cleanup_chezmoi_config() {
    local config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/chezmoi
    local config=$config_dir/chezmoi.toml
    local tmp

    if [ ! -f "$config" ]; then
        return
    fi

    tmp=$(mktemp "${TMPDIR:-/tmp}/chezmoi-aqua-cleanup.XXXXXX")
    awk '
        /^\[/ {
            in_aqua = ($0 == "[data.aqua]")
            in_fish = ($0 == "[data.shell.fish]")
        }
        in_aqua { next }
        in_fish && $0 ~ /^[[:space:]]*portable[[:space:]]*=/ { next }
        { print }
    ' "$config" >"$tmp"

    if cmp -s "$config" "$tmp"; then
        rm -f "$tmp"
        return
    fi

    chmod 600 "$tmp"
    mv "$tmp" "$config"
    echo "Removed stale aqua data from chezmoi config: $config"
}

cleanup_chezmoi_config

remove_file "$HOME/.config/aquaproj-aqua/shared.yaml"
remove_file "$HOME/.config/aquaproj-aqua/fish.yaml"
remove_file "$HOME/.config/aquaproj-aqua/create_local.yaml"
remove_file "$HOME/.config/fish/conf.d/25-aqua.fish"
remove_file "$HOME/.config/fish/conf.d/26-aqua-fish.fish"
remove_file "$HOME/.config/shell/conf.d/25-aqua.sh"
remove_old_starship_fish_config

for command in \
    atuin \
    bat \
    chezmoi \
    delta \
    fastfetch \
    fd \
    fish \
    fish_indent \
    fish_key_reader \
    fzf \
    gh \
    lazygit \
    lsd \
    rg \
    starship \
    yq \
    zoxide
do
    remove_aqua_proxy_link "$HOME/.local/share/aquaproj-aqua/bin/$command"
done

remove_empty_dir "$HOME/.config/aquaproj-aqua"
remove_empty_dir "$HOME/.local/share/aquaproj-aqua/bin"
remove_empty_dir "$HOME/.local/share/aquaproj-aqua"
