"$schema" = "https://github.com/MaaAssistantArknights/maa-cli/raw/main/maa-cli/schemas/cli.schema.json"

[core]
channel = "Beta"

[cli]
channel = "Alpha"

[resource]
# auto_update = true
backend = "libgit2"

[resource.remote]
# branch = "main"
ssh_key = "~/.ssh/id_ed25519"
url = "git@github.com:MaaAssistantArknights/MaaResource.git"
