"$schema" = "https://github.com/MaaAssistantArknights/maa-cli/raw/main/maa-cli/schemas/cli.schema.json"

[resource]
# auto_update = true
backend = "libgit2"

[resource.remote]
# branch = "main"
# ssh_key = "~/.ssh/id_ed25519"
url = "https://git.maa-org.net/MAA/MaaResource"
