[core]
channel = "beta"

[resource]
# auto_update = true
backend = "git"
# backend = "libgit2"

[resource.remote]
# branch = "main"
# ssh_key = "~/.ssh/id_ed25519"
url = "https://git.maa-org.net/MAA/MaaResource"
