packages = [
  "atuin",
  "bat",
  "chezmoi",
  "dust",
  "eza",
  "fastfetch",
  "fd",
  "fish",
  "fzf",
  "gh",
  "git-delta",
  "lazygit",
  "ripgrep",
  "yq",
  "zoxide",
]

[registry.mise]
fish = "aqua:fish-shell/fish-shell"
gh = "github-cli"
git-delta = "delta"

[toolchains]
node = "lts"
bun = "latest"
