ARG CADDY_VERSION=2.11.4
FROM docker.io/library/caddy:${CADDY_VERSION}-builder AS builder
ARG CADDY_VERSION
RUN xcaddy build "${CADDY_VERSION}" --with github.com/caddy-dns/cloudflare@v0.2.4

FROM docker.io/library/caddy:${CADDY_VERSION}
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
