"$schema" = "https://github.com/MaaAssistantArknights/maa-cli/raw/main/maa-cli/schemas/asst.schema.json"

[connection]
adb_path = "~/Library/Android/sdk/platform-tools/adb"
address = "127.0.0.1:5555"
config = "CompatMac"

[instance_options]
touch_mode = "MaaTouch"
deployment_with_pause = false
