#----------------------------- StartUp ----------------------------#
[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }


#----------------------------- Infrast ----------------------------#
[[tasks]]
type = "Infrast"

[tasks.params]
mode = 10000
facility = ["Trade", "Reception", "Mfg", "Control", "Power", "Office", "Dorm"]
dorm_trust_enabled = true
filename = "normal.json"
replenish = true

[[tasks.variants]]
condition = { type = "Time", end = "12:00:00" }
params = { plan_index = 1 }

[[tasks.variants]]
condition = { type = "Time", start = "12:00:00", end = "18:00:00" }
params = { plan_index = 2 }

[[tasks.variants]]
condition = { type = "Time", start = "18:00:00" }
params = { plan_index = 0 }

#------------------------------ Fight -----------------------------#
[[tasks]]
type = "Fight"
strategy = "merge"

[tasks.params]
report_to_penguin = true
penguin_id = "084310065"

# use all expiring medicine on Sunday Evening
[[tasks.variants]]
params = { expiring_medicine = 1000 }

[tasks.variants.condition]
type = "Combined"
conditions = [
  { type = "Time", start = "18:00:00" },
  { type = "Weekday", weekdays = ["Sun"] },
]

# fight 1-7 by default
[[tasks.variants]]
params = { stage = "1-7" }

[[tasks.variants]]
params = { stage = "ZT-8" }
condition = { type = "DateTime", start = "2023-11-01T16:00:00", end = "2023-11-21T03:59:59" }

#------------------------------ Mall ------------------------------#
# Mall after 18:00
[[tasks]]
type = "Mall"
[tasks.params]
shopping = true
credit_fight = true
buy_first = ["招聘许可", "龙门币"]
blacklist = ["碳", "家具", "加急许可"]
[[tasks.variants]]
condition = { type = "Time", start = "18:00:00" }

#----------------------------- Recruit ----------------------------#
# Recruit after 18:00
[[tasks]]
type = "Recruit"

[tasks.params]
refresh = true
select = [4, 5]
confirm = [3, 4, 5]
skip_robot = true
recruitment_time = { '3' = 460 }
report_to_penguin = true
penguin_id = "084310065"

[[tasks.variants]]
condition = { type = "Time", start = "18:00:00" }
params = { times = 4 }

# consume refresh times
[[tasks.variants]]
params = { times = 1 }

#------------------------------ Award -----------------------------#
[[tasks]]
type = "Award"

[tasks.params]
award = true
mail = true

#--------------------------- Close Game ---------------------------#
[[tasks]]
type = "CloseDown"
