#----------------------------- StartUp ----------------------------#
[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }


#----------------------------- Infrast ----------------------------#
[[tasks]]
type = "Infrast"

[tasks.params]
mode = 10000
facility = ["Trade", "Reception", "Mfg", "Control", "Power", "Office", "Dorm"]
dorm_trust_enabled = true
filename = "normal.json"
replenish = true

[[tasks.variants]]
condition = { type = "Time", start = "07:00:00", end = "12:00:00" }
params = { plan_index = { default = 1, description = "index of plan" } }

[[tasks.variants]]
condition = { type = "Time", start = "12:00:00", end = "17:00:00" }
params = { plan_index = { default = 2, description = "index of plan" } }

[[tasks.variants]]
condition = { type = "Time", start = "17:00:00", end = "23:00:00" }
params = { plan_index = { default = 3, description = "index of plan" } }

[[tasks.variants]]
[tasks.variants.params]
facility = []
plan_index = { default = 0, description = "index of plan" }

#------------------------------ Fight -----------------------------#

#============================= Fight 1 ============================#
[[tasks]]
name = "Fight Event Stage"
type = "Fight"
strategy = "merge"

[tasks.params]
report_to_penguin = true
penguin_id = "084310065"

# use all expiring medicine on Sunday
[[tasks.variants]]
params = { expiring_medicine = 1000 }
condition = { type = "Weekday", weekdays = ["Sun"] }

[[tasks.variants]]
params = { stage = "HE-7" }
condition = { type = "OnSideStory", client = "Official" }

#============================= Fight 2 ============================#
[[tasks]]
name = "Fight Fallback"
type = "Fight"
strategy = "merge"

[tasks.params]
report_to_penguin = true
penguin_id = "084310065"

# use all expiring medicine on Sunday
[[tasks.variants]]
params = { expiring_medicine = 1000 }
condition = { type = "Weekday", weekdays = ["Sun"] }

[[tasks.variants]]
params = { stage = "1-7", series = 3 }

#------------------------------ Mall ------------------------------#
# Mall before 7:00
[[tasks]]
type = "Mall"

[tasks.params]
shopping = true
buy_first = ["招聘许可", "龙门币"]
blacklist = ["碳", "家具", "加急许可"]

[[tasks.variants]]
condition = { type = "Time", end = "07:00:00" }
params = { credit_fight = true, select_formation = 4 }

[[tasks.variants]]
params = {}

#----------------------------- Recruit ----------------------------#
[[tasks]]
type = "Recruit"

[tasks.params]
refresh = true
select = [4, 5]
confirm = [3, 4, 5]
skip_robot = false
recruitment_time = { '3' = 460 }
report_to_penguin = true
penguin_id = "084310065"

[[tasks.variants]]
condition = { type = "Time", start = "17:00:00" }
params = { times = 4 }

# consume refresh times
[[tasks.variants]]
params = { times = 1 }

#------------------------------ Award -----------------------------#
[[tasks]]
type = "Award"

[tasks.params]
award = true
mail = true
orundum = true
specialaccess = true

#--------------------------- Close Game ---------------------------#
[[tasks]]
type = "CloseDown"
