#----------------------------- StartUp ----------------------------#
[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }

#------------------------------ Fight -----------------------------#
[[tasks]]
type = "Fight"
[tasks.params]
expiring_medicine = 3
report_to_penguin = true
penguin_id = "084310065"

[[tasks.variants]]
params = { stage = "1-7" }

#--------------------------- Close Game ---------------------------#
[[tasks]]
type = "CloseDown"
