#----------------------------- StartUp ----------------------------#
[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }

#------------------------------ Fight -----------------------------#
[[tasks]]
type = "Fight"
[tasks.params]
expiring_medicine = 3
report_to_penguin = true
penguin_id = "084310065"


# fight the last stage if on event period
[[tasks.variants]]
params = { stage = "SL-8" }
condition = { type = "DateTime", start = "2023-08-01T16:00:00", end = "2023-08-21T03:59:59" }
# fight CE-6 on Tue, Thu, Sat
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue", "Thu", "Sat"] }
params = { stage = "CE-6" }
# fight 1-7 otherwise
[[tasks.variants]]
params = { stage = "1-7" }

#--------------------------- Close Game ---------------------------#
[[tasks]]
type = "CloseDown"
